### ISSUE TITLE
Cannot set LSB

### ISSUE THREAD

**Issue by kwisatz** [RussTheAerialist/node-spi#14]
I was unable to set the bitOrder to least significant bit. In order to set LSB, do I need to use 

```js
this._spi = new spi.Spi( this._config.device.file, {
        "mode": spi.MODE[ this._config.device.mode ],
        "chipSelect": spi.CS[ 'low' ],
        "bitOrder": spi.ORDER[ 'lsb' ],
        "size": 8,
        "maxSpeed": this._config.device.speed
    }, function (spi) {
        spi.open();
        console.log('Initialized spi device: ', util.inspect( spi ));
    } );
```

or 

```js
this._spi = new spi.Spi( this._config.device.file, {
        "mode": spi.MODE[ this._config.device.mode ],
        "chipSelect": spi.CS[ 'low' ],
        "bitOrder": true
        "size": 8,
        "maxSpeed": this._config.device.speed
    }, function (spi) {
        spi.open();
        console.log('Initialized spi device: ', util.inspect( spi ));
    } );
```

The documentation does not agree with the spi.js and spi_binding.cc (lines 150-151) file on this and when trying to use LSB, I get an error message about being unable to set SPI_IOC_WR_MODE.

**Comment by RussTheAerialist** [comment]
Which device are you trying to do this on?  The Raspberry Pi seems to not support LSB mode.  I tried using spidev_test to see if I could get lsb to turn on, but I'm getting the same error message in the kernel log when using spidev_test as when using node-spi.

If you can do a "dmesg", you will see a message that says something like:

```
spidev spi0.0: setup: unsupported mode bits 8
```
This bits = 8 is SPI_LBS_FIRST, so it seems that the raspberry pi doesn't support LSB (the device I was testing on, if it's a different device, please let me know which kind it is, and I'll do some more testing)

**Comment by kwisatz** [comment]
We're communicating with a custom developed microcontroller, so I'm afraid you will not be able to test this. In fact, IIRC, we changed the bit order on the µcontroller to be MSB.
