### ISSUE TITLE
Multiple addresses on spi

### ISSUE THREAD

**Issue by ptorrent** [RussTheAerialist/node-spi#18]
Hi

How can I communicate with different SPI address  ?  By default, I can only commuicate with the first address.

I'm using your module for the piface on raspberry.

Thanks for your support!

**Comment by RussTheAerialist** [comment]
I'm not sure I really follow what you are asking here.  If you turn on chipSelect, you should be able to create multiple SPI objects, each with a different /dev/spi1.x device, and that should allow you to communicate with different devices.

SPI doesn't really support the concept of "addresses".  The way you address multiple devices on a single SPI bus is to toggle the chip select line for the device you want to communicate with, and turn all the others off.  [read more here](https://learn.sparkfun.com/tutorials/serial-peripheral-interface-spi)

**Comment by RussTheAerialist** [comment]
Closing unless I hear back from @ptorrent on the clarification requested.
