### ISSUE TITLE
Error building spi on Raspberry Pi / Raspbian

### ISSUE THREAD

**Issue by fauria** [RussTheAerialist/node-spi#19]
`npm install spi`fails when installing on a Raspberry Pi model B using Raspbian and Node.js 0.10.40.

Output: https://gist.github.com/fauria/3dd003f6570ae241afe8

**Comment by masakij** [comment]
spi@0.2.0 (the latest ver.) requires node 0.12.x.
spi@0.1.2 is an available version with node 0.10.40.

It's described in the README.
>The following versions exist
>
>node-spi 0.1.x - node 0.10.x
>node-spi 0.2 - node 0.12.x

**Comment by RussTheAerialist** [comment]
@masakij has it right.  node api changes, and I haven't had time to migrate to using NaN.  Please install 0.1.x
