### ISSUE TITLE
Does not compile on Raspbian.

### ISSUE THREAD

**Issue by 4rzael** [RussTheAerialist/node-spi#20]
When I try to install it on raspbian (on a RPi2), I get [this error](https://gist.github.com/4rzael/f8e00a79cc7663485424).

My version of g++ is 4.6.3.
My kernel release is 4.1.7-v7+

**Comment by RussTheAerialist** [comment]
From the readme.md file:
* node-spi 0.1.x - node 0.10.x
* node-spi 0.2 - node 0.12.x

You are using node 0.10, and trying to use node-spi-0.1.x

```
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! spi@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
```
