### ISSUE TITLE
SPI values all 0

### ISSUE THREAD

**Issue by GarrettVD** [RussTheAerialist/node-spi#5]
Hi,

The SPI  values when attempting to read form the buffer, all seem to be returning <00 00 00 00 00 00 00 00>.  I can confirm that spidev0.0 is working, as I have a python script that returns appropriate values.

I am interfacing with a MCP3008 ADC chip, using the MOSI, MISO, SCLK and SS pins.

The code is as follows:

```javascript
var Spi = require('spi');

// Read values in from SPI interface
module.exports.readSpi = function() {
  var spiDevice = new Spi.Spi('/dev/spidev0.0', {
    'mode': Spi.MODE['MODE_0']
  }, function (spi) {
    var buf = new Buffer(8);
    spi.read(buf, function(device, retBuf) {
      console.log(device);
      console.log(retBuf);
    });
  });
}

module.exports.readSpi();
```

**Comment by RussTheAerialist** [comment]
I just got around to testing this with the new version of node-spi (out soon).  I was able to get the MCP3008 to read properly.  I set mode 0 and cs low and lowered the maxSpeed to 15000, and that seemed to do the trick.

If you are still having problems (I know it's been 2 years, sorry :/), reopen this issue with details about your setup, and your code so I can help.
