### ISSUE TITLE
Can't send 1 byte message

### ISSUE THREAD

**Issue by thiagorp** [RussTheAerialist/node-spi#9]
I'm getting an error when trying to send a 1 byte message.

From searching on the internet I found that the ioctl returns -1 when it can't send the message, which would make the following code wrong:

```
int ret = ioctl(this->m_fd, SPI_IOC_MESSAGE(1), &data);

if (ret == 1) {
  return ERROR("Unable to send SPI message");
}
```

This is the exact error that I'm getting.

**Comment by RussTheAerialist** [comment]
This was fixed during the update to node 0.12.x and will be included in the node-spi 0.2.0 release.
